package com.yueh.ren.temforecast.model.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yueh.ren.temforecast.model.database.Temper;

import com.yueh.ren.temforecast.model.database.TemperDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig temperDaoConfig;

    private final TemperDao temperDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        temperDaoConfig = daoConfigMap.get(TemperDao.class).clone();
        temperDaoConfig.initIdentityScope(type);

        temperDao = new TemperDao(temperDaoConfig, this);

        registerDao(Temper.class, temperDao);
    }
    
    public void clear() {
        temperDaoConfig.getIdentityScope().clear();
    }

    public TemperDao getTemperDao() {
        return temperDao;
    }

}
