package com.yueh.ren.temforecast.model.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEMPER".
 */
public class Temper {

    /** Not-null value. */
    private String time;
    private double temperature;

    public Temper() {
    }

    public Temper(String time) {
        this.time = time;
    }

    public Temper(String time, double temperature) {
        this.time = time;
        this.temperature = temperature;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    public double getTemperature() {
        return temperature;
    }

    public void setTemperature(double temperature) {
        this.temperature = temperature;
    }

}
